package main

const (
	AUGUST_LEADERBOARD    = "AUGUST_LEADERBOARD"
	SEPTEMBER_LEADERBOARD = "SEPTEMBER_LEADERBOARD"
	OCTOBER_LEADERBOARD   = "OCTOBER_LEADERBOARD"
	GENERAL_LEADERBOARD   = "GENERAL_LEADERBOARD"
	AUGUST_POINT          = "AUGUST_POINT"
	SEPTEMBER_POINT       = "SEPTEMBER_POINT"
	OCTOBER_POINT         = "OCTOBER_POINT"
	GENERAL_POINT         = "GENERAL_POINT"
	WATER_BEST            = "WATER_BEST"
	MELON_BEST            = "MELON_BEST"
	GUMMY_BEST            = "GUMMY_BEST"
	WATERSLIDE            = "WATERSLIDE"
	MELON                 = "MELON"
	GUMMY                 = "GUMMY"
	TOTAL                 = "TOTAL"
	TOTAL_AUGUST          = "TOTAL_AUGUST"
	TOTAL_SEPTEMBER       = "TOTAL_SEPTEMBER"
	TOTAL_OCTOBER         = "TOTAL_OCTOBER"
	TOTAL_GENERAL         = "TOTAL_GENERAL"
	LOGIN_COUNT           = "LOGIN_COUNT"
)
