logger:
  level: "INFO"
socket:
  outgoing_queue_size: 256
  max_message_size_bytes: 4096
  max_request_size_bytes: 131072
matchmaker:
  max_tickets: 1
  interval_sec: 5
  max_intervals: 2
runtime:
  path: "/home/admin/main.ibkmeta.link"
  env:
    - TEST=TEST
